{% set name = "jupyter_server_fileid" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 521608bb87f606a8637fcbdce2f3d24a8b3cc89d2eef61751cb40e468d4e54be

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jupyter-fileid = jupyter_server_fileid.cli:main
  skip: True # [py<37]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.0
  run:
    - python
    - jupyter_server >=1.15,<3
    - jupyter_events >=0.5.0
    - click

test:
  source_files:
    - tests
    - conftest.py
    - pyproject.toml
  imports:
    - jupyter_server_fileid
  commands:
    - pip check
    - jupyter-fileid --help
    - pytest -v
  requires:
    - pip
    - pytest
    - jupyter_server >=1.15, <3
    - pytest-jupyter
    - pytest-cov

about:
  home: https://github.com/jupyter-server/jupyter_server_fileid
  summary: A Jupyter Server extension providing an implementation of the File ID service.
  description: |
    A Jupyter Server extension providing an implementation of the File ID service.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/jupyter-server/jupyter_server_fileid
  doc_url: https://jupyter-server-fileid.readthedocs.io/

extra:
  recipe-maintainers:
    - davidbrochart
    - dlqqq
    - fcollonval
